//
//  MockData.swift
//  Airbnb
//
//  Created by Lokesh on 14/09/25.
//

import Foundation
 

class MockData {
      static let shared = MockData()
    var listing: [Listing] = [
        .init(
            id: UUID().uuidString,
            ownerId: UUID().uuidString,
            ownerName: "Lokesh Kumar",
            ownerImageUrl: "male-profile-photo",
            numberOfBedrooms: 4,
            numberOfBathrooms: 3,
            numberOfGuests: 4,
            numberOfBeds: 4,
            pricePerNights: 12816,
            latitude: 25.7850,
            longitude: -80.196,
            imageURLs: ["bnb1","bnb9", "bnb4", "bnb7"],
            address: "D1 Stay. 3BHK Luxury Apartment in Central Jaipur",
            city: "Jaipur",
            state: "Rajasthan",
            title: "D1 Stay",
            rating: 4.86,
            feature: [.selfCheckIn, .superHost],
            amenities: [.wifi,.alarmSystem,.balcony,.laundry,.tv],
            types: .villa
        ),
        .init(
            id: UUID().uuidString,
            ownerId: UUID().uuidString,
            ownerName: "Manvendra Singh",
            ownerImageUrl: "male-profile-photo",
            numberOfBedrooms: 4,
            numberOfBathrooms: 3,
            numberOfGuests: 4,
            numberOfBeds: 4,
            pricePerNights: 2199,
            latitude: 25.7650,
            longitude: -40.1936,
            imageURLs: ["bnb8","bnb1", "bnb4", "bnb7"],
            address: "C2phae Entire apartment in Dehradun, India",
            city: "Dehradun",
            state: "Uttrakhand",
            title: "Rishyana Homes,Luxurious Apartment Near Mussoorie",
            rating: 4.96,
            feature: [.selfCheckIn,.superHost],
            amenities: [.wifi,.alarmSystem,.tv,.kitchen,.office],
            types: .house
        ),
        
            .init(
                id: UUID().uuidString,
                ownerId: UUID().uuidString,
                ownerName: "shyam Pal",
                ownerImageUrl: "male-profile-photo",
                numberOfBedrooms: 4,
                numberOfBathrooms: 3,
                numberOfGuests: 4,
                numberOfBeds: 4,
                pricePerNights: 5000,
                latitude: 21.7650,
                longitude: -4.1936,
                imageURLs: ["bnb4","bnb3", "bnb4", "bnb9"],
                address: "seaphase-101 The Colva Diaries goa, India",
                city: "Colva",
                state: "Goa",
                title: "PALM CREST The Colva Diaries- 1BHK Apartment",
                rating: 4.96,
                feature: [.selfCheckIn,.superHost],
                amenities: [.wifi,.alarmSystem,.tv,.kitchen,.office],
                types: .house
            ),
        
            .init(
                id: UUID().uuidString,
                ownerId: UUID().uuidString,
                ownerName: "shyam Pal",
                ownerImageUrl: "male-profile-photo",
                numberOfBedrooms: 4,
                numberOfBathrooms: 3,
                numberOfGuests: 4,
                numberOfBeds: 4,
                pricePerNights: 14800,
                latitude: 21.7650,
                longitude: -4.1936,
                imageURLs: ["bnb6","bnb1", "bnb4", "bnb3"],
                address: "sec 11 Entire rental unit in Noida, India",
                city: "Noida",
                state: "UttraPradesh",
                title: "3BHK apartment near Indraprastha Apollo Hospital",
                rating: 4.96,
                feature: [.selfCheckIn,.superHost],
                amenities: [.wifi,.alarmSystem,.tv,.kitchen,.office],
                types: .house
            ),
        .init(
            id: UUID().uuidString,
            ownerId: UUID().uuidString,
            ownerName: "Shubham",
            ownerImageUrl: "male-profile-photo",
            numberOfBedrooms: 4,
            numberOfBathrooms: 3,
            numberOfGuests: 4,
            numberOfBeds: 4,
            pricePerNights: 14800,
            latitude: 21.7650,
            longitude: 40.1936,
            imageURLs: ["bnb10","bnb7", "bnb3", "bnb5"],
            address: "Maya flyOver Indirapura Entire rental unit in Ghaziabad, India",
            city: "Ghaziabad",
            state: "UttraPradesh",
            title: "Lumi Stays - Luxury Studio Apartment",
            rating: 5.0,
            feature: [.selfCheckIn,.superHost],
            amenities: [.wifi,.alarmSystem,.tv,.kitchen,.office],
            types: .house
        ),
        .init(
            id: UUID().uuidString,
            ownerId: UUID().uuidString,
            ownerName: "Shubham",
            ownerImageUrl: "male-profile-photo",
            numberOfBedrooms: 4,
            numberOfBathrooms: 3,
            numberOfGuests: 4,
            numberOfBeds: 4,
            pricePerNights: 14800,
            latitude: 2.7650,
            longitude: 9.1936,
            imageURLs: ["bnb7","bnb2", "bnb3", "bnb1"],
            address: "Entire guest suite in Bangalore Urban, India",
            city: "Bengaluru",
            state: "Karnataka",
            title: "Cozy Penthouse-Style 1 BHK",
            rating: 4.98,
            feature: [.selfCheckIn,.superHost],
            amenities: [.wifi,.alarmSystem,.tv,.kitchen,.office],
            types: .house
        ),
        .init(
            id: UUID().uuidString,
            ownerId: UUID().uuidString,
            ownerName: "Rakshit",
            ownerImageUrl: "male-profile-photo",
            numberOfBedrooms: 4,
            numberOfBathrooms: 3,
            numberOfGuests: 4,
            numberOfBeds: 4,
            pricePerNights: 14800,
            latitude: 22.7650,
            longitude: 21.1936,
            imageURLs: ["bnb2","bnb5", "bnb9", "bnb1"],
            address: "GK phase 1 Entire serviced apartment in New Delhi, India",
            city: "Greater Kailash",
            state: "NewDelhi",
            title: "MES Secret Hide-Out Beautiful Terrace BedRm Lounge",
            rating: 5.0,
            feature: [.selfCheckIn,.superHost],
            amenities: [.wifi,.alarmSystem,.tv,.kitchen,.office],
            types: .house
        ),
        
    ]
}
